In [1]:
# Sort, Search & Counting Function.

In [2]:
import numpy as np

In [3]:
arr=np.array([4,6,7,77,5,0,5,44,23,55,98,65])

In [4]:
arr

array([ 4,  6,  7, 77,  5,  0,  5, 44, 23, 55, 98, 65])

In [6]:
np.sort(arr)

array([ 0,  4,  5,  5,  6,  7, 23, 44, 55, 65, 77, 98])

In [7]:
np.searchsorted(arr,79)

12

In [8]:
arr1=np.array([0,345,454,0,0,0,0])

In [9]:
np.count_nonzero(arr1)

2

In [10]:
arr

array([ 4,  6,  7, 77,  5,  0,  5, 44, 23, 55, 98, 65])

In [11]:
np.where(arr>6)

(array([ 2,  3,  7,  8,  9, 10, 11]),)

In [12]:
np.extract(arr>3,arr)

array([ 4,  6,  7, 77,  5,  5, 44, 23, 55, 98, 65])

In [13]:
#Numpy -Byte Swaping


In [14]:
arr

array([ 4,  6,  7, 77,  5,  0,  5, 44, 23, 55, 98, 65])

In [15]:
arr.byteswap()

array([ 288230376151711744,  432345564227567616,  504403158265495552,
       5548434740920451072,  360287970189639680,                   0,
        360287970189639680, 3170534137668829184, 1657324662872342528,
       3963167672086036480, 7061644215716937728, 4683743612465315840])

In [16]:
#Numpy - Copy-& Views.

In [17]:
arr

array([ 4,  6,  7, 77,  5,  0,  5, 44, 23, 55, 98, 65])

In [18]:
a=np.copy(arr)

In [20]:
a

array([ 4,  6,  7, 77,  5,  0,  5, 44, 23, 55, 98, 65])

In [25]:
b=arr.view()

In [26]:
b

array([67,  6,  7, 77,  5,  0,  5, 44, 23, 55, 98, 65])

In [27]:
arr

array([67,  6,  7, 77,  5,  0,  5, 44, 23, 55, 98, 65])

In [28]:
# Numpy - matrix Library

In [29]:
import numpy.matlib as nm

In [30]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [33]:
# Nunpy- Linear Algebra 

In [34]:
arr1=np.random.randint([[2,3],[4,5]])
arr2=np.random.randint([[5,3],[2,5]])

In [35]:
np.dot(arr1,arr2)

array([[3, 2],
       [9, 8]])

In [36]:
arr1@arr2

array([[3, 2],
       [9, 8]])