In [1]:
import numpy as np

In [2]:
# Numpy -Array Manipulaion

In [3]:
arr=np.random.randint(1,10,(3,4))

In [4]:
arr

array([[2, 9, 7, 1],
       [7, 9, 5, 2],
       [7, 5, 3, 3]])

In [5]:
arr.reshape(6,2)

array([[2, 9],
       [7, 1],
       [7, 9],
       [5, 2],
       [7, 5],
       [3, 3]])

In [6]:
arr.reshape(2,6)

array([[2, 9, 7, 1, 7, 9],
       [5, 2, 7, 5, 3, 3]])

In [7]:
arr.T

array([[2, 7, 7],
       [9, 9, 5],
       [7, 5, 3],
       [1, 2, 3]])

In [8]:
arr.flatten()

array([2, 9, 7, 1, 7, 9, 5, 2, 7, 5, 3, 3])

In [9]:
arr1=np.array([1,2,3,3,4])

In [10]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [12]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [13]:
arr

array([[2, 9, 7, 1],
       [7, 9, 5, 2],
       [7, 5, 3, 3]])

In [14]:
np.squeeze(arr)

array([[2, 9, 7, 1],
       [7, 9, 5, 2],
       [7, 5, 3, 3]])

In [15]:
data=np.array([[1],[2],[3]])

In [16]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [20]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [21]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [22]:
#Numpy -binary Opration

In [23]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [24]:
arr1

array([[8, 4, 1, 6],
       [9, 1, 7, 5],
       [1, 1, 9, 7]])

In [25]:
arr2

array([[2, 4, 4, 1],
       [4, 5, 2, 5],
       [3, 4, 5, 6]])

In [26]:
arr1+arr2

array([[10,  8,  5,  7],
       [13,  6,  9, 10],
       [ 4,  5, 14, 13]])

In [27]:
#Numpy -String Function

In [29]:
arr=np.array(["suraj","sandhya"])

In [30]:
np.char.upper(arr)

array(['SURAJ', 'SANDHYA'], dtype='<U7')

In [31]:
np.char.title(arr)

array(['Suraj', 'Sandhya'], dtype='<U7')

In [32]:
#Numpy -Mathematical Function.

In [33]:
arr1

array([[8, 4, 1, 6],
       [9, 1, 7, 5],
       [1, 1, 9, 7]])

In [34]:
np.sin(arr1)

array([[ 0.98935825, -0.7568025 ,  0.84147098, -0.2794155 ],
       [ 0.41211849,  0.84147098,  0.6569866 , -0.95892427],
       [ 0.84147098,  0.84147098,  0.41211849,  0.6569866 ]])

In [35]:
np.cos(arr1)

array([[-0.14550003, -0.65364362,  0.54030231,  0.96017029],
       [-0.91113026,  0.54030231,  0.75390225,  0.28366219],
       [ 0.54030231,  0.54030231, -0.91113026,  0.75390225]])

In [36]:
np.tan(arr1)

array([[-6.79971146,  1.15782128,  1.55740772, -0.29100619],
       [-0.45231566,  1.55740772,  0.87144798, -3.38051501],
       [ 1.55740772,  1.55740772, -0.45231566,  0.87144798]])

In [37]:
np.tanh(arr1)

array([[0.99999977, 0.9993293 , 0.76159416, 0.99998771],
       [0.99999997, 0.76159416, 0.99999834, 0.9999092 ],
       [0.76159416, 0.76159416, 0.99999997, 0.99999834]])

In [38]:
np.log(arr1)

array([[2.07944154, 1.38629436, 0.        , 1.79175947],
       [2.19722458, 0.        , 1.94591015, 1.60943791],
       [0.        , 0.        , 2.19722458, 1.94591015]])

In [39]:
np.exp(arr1)

array([[2.98095799e+03, 5.45981500e+01, 2.71828183e+00, 4.03428793e+02],
       [8.10308393e+03, 2.71828183e+00, 1.09663316e+03, 1.48413159e+02],
       [2.71828183e+00, 2.71828183e+00, 8.10308393e+03, 1.09663316e+03]])

In [40]:
np.log10(arr1)

array([[0.90308999, 0.60205999, 0.        , 0.77815125],
       [0.95424251, 0.        , 0.84509804, 0.69897   ],
       [0.        , 0.        , 0.95424251, 0.84509804]])

In [41]:
np.sqrt(arr1)

array([[2.82842712, 2.        , 1.        , 2.44948974],
       [3.        , 1.        , 2.64575131, 2.23606798],
       [1.        , 1.        , 3.        , 2.64575131]])

In [42]:
np.power(arr1,2)

array([[64, 16,  1, 36],
       [81,  1, 49, 25],
       [ 1,  1, 81, 49]])

In [43]:
np.mean(arr1)

4.916666666666667

In [44]:
np.std(arr1)

3.0945741046045234