In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
l=[1,2,3,4,5,6]

In [7]:
ar=np.array(l)

In [8]:
type(ar)

numpy.ndarray

In [10]:
arr1=np.array([[1,2],[3,4]])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [13]:
a=[2,3,4]

In [14]:
np.asanyarray(a)

array([2, 3, 4])

In [15]:
b=np.matrix(l)

In [16]:
b

matrix([[1, 2, 3, 4, 5, 6]])

In [17]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5, 6]])

In [18]:
a=np.array(l)


In [19]:
a

array([1, 2, 3, 4, 5, 6])

In [20]:
c=a

In [21]:
c

array([1, 2, 3, 4, 5, 6])

In [22]:
a

array([1, 2, 3, 4, 5, 6])

In [23]:
c[0]=100

In [24]:
c

array([100,   2,   3,   4,   5,   6])

In [25]:
d=np.copy(a)

In [26]:
d

array([100,   2,   3,   4,   5,   6])

In [27]:
a

array([100,   2,   3,   4,   5,   6])

In [28]:
a[1]=400

In [29]:
d

array([100,   2,   3,   4,   5,   6])

In [30]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
 itereble=(i*i for i in range(5))

In [33]:
np.fromiter( itereble,float)

array([ 0.,  1.,  4.,  9., 16.])

In [34]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [36]:
np.fromstring('2,4', sep=' ,')

array([2., 4.])

In [37]:
# Numpy-Data Types

In [38]:
l=[2,3,4,5,6]

In [39]:
ar=np.array(l)

In [40]:
ar

array([2, 3, 4, 5, 6])

In [41]:
ar.ndim

1

In [42]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [43]:
ar2.ndim

2

In [44]:
ar.size

5

In [45]:
ar2.size

8

In [46]:
ar

array([2, 3, 4, 5, 6])

In [47]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [48]:
ar.shape

(5,)

In [50]:
ar2.shape

(2, 4)

In [52]:
ar.dtype

dtype('int64')

In [53]:
ar2.dtype

dtype('int64')

In [54]:
ar22=np.array([(1.4,45,45),(23,45,66)])

In [55]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [56]:
ar22.dtype

dtype('float64')

In [58]:
list(range(5))

[0, 1, 2, 3, 4]

In [60]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [63]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [71]:
ar4=np.zeros((3,4,2,3))

In [72]:
ar4.ndim

4

In [73]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [76]:
on=np.ones((2,3,2))

In [77]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [78]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [79]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [82]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [83]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [86]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [89]:
arr=np.random.randn(3,4)

In [88]:
import pandas as pd

In [90]:
pd.DataFrame(arr)

0         1         2         3
0  0.106778 -0.053142  0.129482 -0.213118
1  0.470760 -0.563650 -0.991968  0.984214
2 -0.807096 -0.745373 -1.493909 -0.726321

In [92]:
np.random.rand(3,4)

array([[0.3221038 , 0.56571013, 0.28936346, 0.91861603],
       [0.60700796, 0.61144597, 0.87879284, 0.33104933],
       [0.1174871 , 0.42646097, 0.76418659, 0.88616987]])

In [96]:
np.random.randint(1,110,(300,400))

array([[  8,  32,  14, ...,  28,  43,  78],
       [ 63,  49,  56, ...,  97,  89, 101],
       [ 85,  19,  54, ...,  71,  61,  51],
       ...,
       [ 41,  54,  32, ...,  79,   6,  87],
       [ 11,  79,  33, ...,  67,  98,  92],
       [ 95,  43,  17, ...,  43,  19, 103]])

In [99]:
pd.DataFrame(pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("test.csv"))

Empty DataFrame
Columns: []
Index: []

In [100]:
arr=np.random.rand(3,4)

In [101]:
arr

array([[0.09186212, 0.0182769 , 0.15134001, 0.36638776],
       [0.80883836, 0.6927235 , 0.38172059, 0.0594784 ],
       [0.91138924, 0.12373686, 0.69465392, 0.79447591]])

In [102]:
arr.reshape(6,2)

array([[0.09186212, 0.0182769 ],
       [0.15134001, 0.36638776],
       [0.80883836, 0.6927235 ],
       [0.38172059, 0.0594784 ],
       [0.91138924, 0.12373686],
       [0.69465392, 0.79447591]])

In [105]:
arr1=arr.reshape(6,-1)## koi bhi nagetive number dedo

In [109]:
arr1[1][1]

0.36638776409050233

In [110]:
arr1

array([[0.09186212, 0.0182769 ],
       [0.15134001, 0.36638776],
       [0.80883836, 0.6927235 ],
       [0.38172059, 0.0594784 ],
       [0.91138924, 0.12373686],
       [0.69465392, 0.79447591]])

In [116]:
arr1[2:5,1]

array([0.6927235 , 0.0594784 , 0.12373686])

In [118]:
arr=np.random.randint(1,100,(5,5))

In [119]:
arr

array([[43, 58, 53, 28, 64],
       [44, 34, 98, 85, 49],
       [60, 65, 55, 89, 22],
       [74, 81, 77, 87, 74],
       [ 6, 71, 40, 16, 83]])

In [121]:
arr[arr>50]

array([58, 53, 64, 98, 85, 60, 65, 55, 89, 74, 81, 77, 87, 74, 71, 83])

In [122]:
arr

array([[43, 58, 53, 28, 64],
       [44, 34, 98, 85, 49],
       [60, 65, 55, 89, 22],
       [74, 81, 77, 87, 74],
       [ 6, 71, 40, 16, 83]])

In [123]:
arr[2:4,[1,2]]

array([[65, 55],
       [81, 77]])

In [127]:
arr[0:2,[2,3]]

array([[53, 28],
       [98, 85]])

In [128]:
arr[1:3,[2,3]]

array([[98, 85],
       [55, 89]])

In [132]:
arr[0][0]=4000

In [133]:
arr

array([[4000,   58,   53,   28,   64],
       [  44,   34,   98,   85,   49],
       [  60,   65,   55,   89,   22],
       [  74,   81,   77,   87,   74],
       [   6,   71,   40,   16,   83]])

In [139]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [140]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [1, 2, 2]])

In [141]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [142]:
arr1+arr2

array([[2, 3, 2],
       [2, 3, 4],
       [2, 4, 4]])

In [143]:
arr1*arr2

array([[1, 2, 1],
       [1, 2, 4],
       [1, 4, 4]])

In [144]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0, -1,  0],
       [ 0,  0,  0]])

In [145]:
arr1/arr2

array([[1. , 2. , 1. ],
       [1. , 0.5, 1. ],
       [1. , 1. , 1. ]])

In [146]:
arr1*arr2

array([[1, 2, 1],
       [1, 2, 4],
       [1, 4, 4]])

In [147]:
arr1@arr2

array([[4, 7, 7],
       [4, 7, 7],
       [5, 9, 9]])

In [148]:
arr1/0

/tmp/ipykernel_83/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [149]:
arr1+100

array([[101, 102, 101],
       [101, 101, 102],
       [101, 102, 102]])

In [150]:
arr1**2

array([[1, 4, 1],
       [1, 1, 4],
       [1, 4, 4]])

In [151]:
#Numpy-Brodcasting

In [157]:
arr=np.zeros((4,4))

In [154]:
row=np.array([1,2,3,4])

In [156]:
row

array([1, 2, 3, 4])

In [158]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [159]:
row.T

array([1, 2, 3, 4])

In [161]:
col=np.array([[1,2,3,4]])

In [162]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [163]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [164]:
np.random.randint(1,4,(3,4))

array([[2, 3, 1, 3],
       [3, 1, 3, 3],
       [2, 2, 1, 3]])

In [165]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356]])

In [168]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [167]:
np.log10(arr1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.30103]])